StartupEvents.registry('fluid', event => {
  event.create('heavy_chromatic_fluid')
    .thickTexture(0x441f30)
    .bucketColor(0x441f30)
    .displayName('Heavy Chromatic Fluid')
  event.create('chromatic_fluid')
    .thickTexture(0x683466)
    .bucketColor(0x683466)
    .displayName('Chromatic Fluid')
  event.create('quantum_infusion')
    .thinTexture(0x372f65)
    .bucketColor(0x372f65)
    .displayName('Quantum Infusion')
  event.create('void_essence')
    .thinTexture(0x38304d)
    .bucketColor(0x38304d)
    .displayName('Void Essence')
  event.create('volatile_sky_solution')
    .thickTexture(0x2E3331)
    .bucketColor(0x2E3331)
    .displayName('Volatile Sky Solution')
})